//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int Id { get; set; }
        public string Proveedor1 { get; set; }
        public string CUIT { get; set; }
        public string Mail { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
